### PR TITLE
Update all pacakges and remove generateUuid

### PR DESCRIPTION
**Pull request by vip30**
Replace generateUuid by useId

fix

https://github.com/justinmahar/react-social-media-embed/issues/7
https://github.com/justinmahar/react-social-media-embed/issues/40

### CODE REVIEW

**Comment by justinmahar** [comment]
@vip30 Awesome, will be addressing this PR this weekend

**Comment by justinmahar** [comment]
First I've learned of React.useId(), so much nicer

**Comment by justinmahar** [comment]
I reviewed these and they looked good, but had to revert the changes, unfortunately. They broke the Storybook build, see https://github.com/justinmahar/react-social-media-embed/pull/55

**Comment by justinmahar** [comment]
Did this run or build for you locally? The issue occurs with both `npm start` and in production (GitHub Pages).

**Comment by vip30** [comment]
Lemme try for storybook 
We already use the fixed commit in production so should be ok for the plugin itself

**Comment by vip30** [comment]
should be ok now @justinmahar, just missing to update those mdx files.

**Pull request merged**
